# Generated by Django 3.1.7 on 2021-06-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmail',
            name='file',
        ),
        migrations.AddField(
            model_name='gmail',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gmail',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='make_spam',
            field=models.BooleanField(default=False),
        ),
    ]
